name: use-secrets-workflow
on: ['push']
jobs:
  echo-hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-hello-world-step
        run: echo "Hello World"
  echo-secrets-my-secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-secrets-my-secret-step
        run: echo "My secret is masked ${{ secrets.MY_SECRET }}"
